import type { Category, Product } from "./types";

export const STARTER_CATEGORIES: Category[] = [
  { id: "cat-dryfruits", name: "Dry Fruits & Gift Boxes (सुकामेवा व बॉक्सेस)" },
  { id: "cat-agarbatti", name: "Agarbatti (अगरबत्ती)" },
  { id: "cat-dhoop", name: "Dhoop Cones (धूप कोन्स)" },
  { id: "cat-kitchen", name: "Kitchen Essentials (किचन व दैनंदिन)" },
];

export const STARTER_PRODUCTS: Product[] = [
  // --- Dry Fruits & Diwali Boxes ---
  {
    id: "df-cashew-500g",
    category_id: "cat-dryfruits",
    name: "Premium Cashew / काजू (W240 Grade 500g)",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp"],
    is_image: true,
    mrp: 650,
    member_price: 590,
    wholesale_enabled: true,
    wholesale_price: 520,
    wholesale_min_qty: 10,
    is_available: true,
  },
  {
    id: "df-almonds-500g",
    category_id: "cat-dryfruits",
    name: "California Almonds / बदाम (500g)",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp"],
    is_image: true,
    mrp: 690,
    member_price: 620,
    wholesale_enabled: true,
    wholesale_price: 575,
    wholesale_min_qty: 10,
    is_available: true,
  },
  {
    id: "df-pista-500g",
    category_id: "cat-dryfruits",
    name: "Jumbo Salted Pista / पिस्ता (500g)",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp"],
    is_image: true,
    mrp: 950,
    member_price: 870,
    wholesale_enabled: true,
    wholesale_price: 820,
    wholesale_min_qty: 10,
    is_available: true,
  },
  {
    id: "df-raisins-yellow-500g",
    category_id: "cat-dryfruits",
    name: "Golden Yellow Raisins / पिवळे बेदाणे (500g)",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp"],
    is_image: true,
    mrp: 320,
    member_price: 270,
    wholesale_enabled: true,
    wholesale_price: 230,
    wholesale_min_qty: 10,
    is_available: true,
  },
  {
    id: "df-raisins-black-500g",
    category_id: "cat-dryfruits",
    name: "Black Raisins / काळे मनुके (500g)",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp"],
    is_image: true,
    mrp: 220,
    member_price: 180,
    wholesale_enabled: true,
    wholesale_price: 150,
    wholesale_min_qty: 10,
    is_available: true,
  },
  {
    id: "df-anjeer-500g",
    category_id: "cat-dryfruits",
    name: "Afghani Anjeer / अंजीर (500g)",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp"],
    is_image: true,
    mrp: 980,
    member_price: 890,
    wholesale_enabled: true,
    wholesale_price: 820,
    wholesale_min_qty: 10,
    is_available: true,
  },
  {
    id: "df-walnut-500g",
    category_id: "cat-dryfruits",
    name: "Akrod Walnut Kernels / अक्रोड मगज (500g)",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199352/venkateshwara/products/cashew-500g.webp"],
    is_image: true,
    mrp: 950,
    member_price: 860,
    wholesale_enabled: true,
    wholesale_price: 800,
    wholesale_min_qty: 10,
    is_available: true,
  },
  {
    id: "diwali-box-4-50g",
    category_id: "cat-dryfruits",
    name: "Diwali Gift Box: 4 Mini Boxes × 50g (200g Net)",
    image_url: "/diwali/box-4.jpg",
    images: ["/diwali/box-4.jpg"],
    is_image: true,
    mrp: 240,
    member_price: 240,
    wholesale_enabled: true,
    wholesale_price: 225,
    wholesale_min_qty: 10,
    is_available: true,
  },
  {
    id: "diwali-box-4-100g",
    category_id: "cat-dryfruits",
    name: "Diwali Gift Box: 4 Mini Boxes × 100g (400g Net)",
    image_url: "/diwali/box-4.jpg",
    images: ["/diwali/box-4.jpg"],
    is_image: true,
    mrp: 450,
    member_price: 450,
    wholesale_enabled: true,
    wholesale_price: 430,
    wholesale_min_qty: 10,
    is_available: true,
  },
  {
    id: "diwali-box-6-50g",
    category_id: "cat-dryfruits",
    name: "Diwali Gift Box: 6 Mini Boxes × 50g (300g Net)",
    image_url: "/diwali/box-6.jpg",
    images: ["/diwali/box-6.jpg"],
    is_image: true,
    mrp: 330,
    member_price: 330,
    wholesale_enabled: true,
    wholesale_price: 315,
    wholesale_min_qty: 10,
    is_available: true,
  },
  {
    id: "diwali-box-6-100g",
    category_id: "cat-dryfruits",
    name: "Diwali Gift Box: 6 Mini Boxes × 100g (600g Net)",
    image_url: "/diwali/box-6.jpg",
    images: ["/diwali/box-6.jpg"],
    is_image: true,
    mrp: 640,
    member_price: 640,
    wholesale_enabled: true,
    wholesale_price: 610,
    wholesale_min_qty: 10,
    is_available: true,
  },

  // --- Agarbatti ---
  {
    id: "agarbatti-bottle-7",
    category_id: "cat-agarbatti",
    name: "Agarbatti Bottle (7 Fragrances: Mogra, Kasturi, Kesar Chandan, Ayodhya, Sainath, Woods, Geranium)",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199347/venkateshwara/products/agarbatti-ayodhya.webp",
    images: [
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199350/venkateshwara/products/agarbatti-mogra.webp",
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199348/venkateshwara/products/agarbatti-kasturi.webp",
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199349/venkateshwara/products/agarbatti-kesar-chandan.webp",
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199347/venkateshwara/products/agarbatti-ayodhya.webp",
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199351/venkateshwara/products/agarbatti-sainath.webp",
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199351/venkateshwara/products/agarbatti-woods.webp",
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199348/venkateshwara/products/agarbatti-geranium.webp",
    ],
    is_image: true,
    mrp: 130,
    member_price: 45,
    wholesale_enabled: true,
    wholesale_price: 35,
    wholesale_min_qty: 70,
    is_available: true,
  },
  {
    id: "agarbatti-pouch-4",
    category_id: "cat-agarbatti",
    name: "Agarbatti Pouch 100g (4 Fragrances: Ayodhya, Kasturi, Mogra, Woods)",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199355/venkateshwara/products/pouch-ayodhya.webp",
    images: [
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199355/venkateshwara/products/pouch-ayodhya.webp",
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199356/venkateshwara/products/pouch-kasturi.webp",
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199357/venkateshwara/products/pouch-mogra.webp",
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199357/venkateshwara/products/pouch-woods.webp",
    ],
    is_image: true,
    mrp: 100,
    member_price: 45,
    wholesale_enabled: true,
    wholesale_price: 35,
    wholesale_min_qty: 60,
    is_available: true,
  },
  {
    id: "agarbatti-5-in-1",
    category_id: "cat-agarbatti",
    name: "5 in 1 Panchagavya Agarbatti / पंचगव्य अगरबत्ती",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199346/venkateshwara/products/agarbatti-5-in-1.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199346/venkateshwara/products/agarbatti-5-in-1.webp"],
    is_image: true,
    mrp: 450,
    member_price: 399,
    wholesale_enabled: true,
    wholesale_price: 360,
    wholesale_min_qty: 6,
    is_available: true,
  },
  {
    id: "agarbatti-ayodhya",
    category_id: "cat-agarbatti",
    name: "Ayodhya Agarbatti / अयोध्या अगरबत्ती",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199347/venkateshwara/products/agarbatti-ayodhya.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199347/venkateshwara/products/agarbatti-ayodhya.webp"],
    is_image: true,
    mrp: 120,
    member_price: 100,
    wholesale_enabled: true,
    wholesale_price: 85,
    wholesale_min_qty: 12,
    is_available: true,
  },
  {
    id: "agarbatti-kasturi",
    category_id: "cat-agarbatti",
    name: "Kasturi Agarbatti / कस्तुरी अगरबत्ती",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199348/venkateshwara/products/agarbatti-kasturi.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199348/venkateshwara/products/agarbatti-kasturi.webp"],
    is_image: true,
    mrp: 120,
    member_price: 100,
    wholesale_enabled: true,
    wholesale_price: 85,
    wholesale_min_qty: 12,
    is_available: true,
  },
  {
    id: "agarbatti-mogra",
    category_id: "cat-agarbatti",
    name: "Mogra Agarbatti / मोगरा अगरबत्ती",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199350/venkateshwara/products/agarbatti-mogra.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199350/venkateshwara/products/agarbatti-mogra.webp"],
    is_image: true,
    mrp: 120,
    member_price: 100,
    wholesale_enabled: true,
    wholesale_price: 85,
    wholesale_min_qty: 12,
    is_available: true,
  },
  {
    id: "agarbatti-woods",
    category_id: "cat-agarbatti",
    name: "Woods Agarbatti / वूड्स अगरबत्ती",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199351/venkateshwara/products/agarbatti-woods.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199351/venkateshwara/products/agarbatti-woods.webp"],
    is_image: true,
    mrp: 120,
    member_price: 100,
    wholesale_enabled: false,
    wholesale_price: null,
    wholesale_min_qty: null,
    is_available: true,
  },
  {
    id: "agarbatti-sainath",
    category_id: "cat-agarbatti",
    name: "Sainath Flora Agarbatti / साईनाथ फ्लोरा अगरबत्ती",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199351/venkateshwara/products/agarbatti-sainath.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199351/venkateshwara/products/agarbatti-sainath.webp"],
    is_image: true,
    mrp: 120,
    member_price: 100,
    wholesale_enabled: false,
    wholesale_price: null,
    wholesale_min_qty: null,
    is_available: true,
  },
  {
    id: "agarbatti-geranium",
    category_id: "cat-agarbatti",
    name: "Geranium Agarbatti / जिरेनियम अगरबत्ती",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199348/venkateshwara/products/agarbatti-geranium.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199348/venkateshwara/products/agarbatti-geranium.webp"],
    is_image: true,
    mrp: 120,
    member_price: 100,
    wholesale_enabled: false,
    wholesale_price: null,
    wholesale_min_qty: null,
    is_available: true,
  },
  {
    id: "agarbatti-kesar-chandan",
    category_id: "cat-agarbatti",
    name: "Kesar Chandan Agarbatti / केशर चंदन अगरबत्ती",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199349/venkateshwara/products/agarbatti-kesar-chandan.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199349/venkateshwara/products/agarbatti-kesar-chandan.webp"],
    is_image: true,
    mrp: 120,
    member_price: 100,
    wholesale_enabled: false,
    wholesale_price: null,
    wholesale_min_qty: null,
    is_available: true,
  },

  // --- Dhoop Cones ---
  {
    id: "dhoop-cones-100g-3",
    category_id: "cat-dhoop",
    name: "Dhoop Cones 100g (Astha, Vedshree, Vrinda)",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199353/venkateshwara/products/dhoop-astha.webp",
    images: [
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199353/venkateshwara/products/dhoop-astha.webp",
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199353/venkateshwara/products/dhoop-vedshree.webp",
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199354/venkateshwara/products/dhoop-vrinda.webp",
    ],
    is_image: true,
    mrp: 250,
    member_price: 65,
    wholesale_enabled: true,
    wholesale_price: 55,
    wholesale_min_qty: 60,
    is_available: true,
  },
  {
    id: "dhoop-cones-50g-3",
    category_id: "cat-dhoop",
    name: "Dhoop Cones 50g (Astha, Vedshree, Vrinda)",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199353/venkateshwara/products/dhoop-astha.webp",
    images: [
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199353/venkateshwara/products/dhoop-astha.webp",
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199353/venkateshwara/products/dhoop-vedshree.webp",
      "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199354/venkateshwara/products/dhoop-vrinda.webp",
    ],
    is_image: true,
    mrp: 125,
    member_price: 40,
    wholesale_enabled: true,
    wholesale_price: 37,
    wholesale_min_qty: 60,
    is_available: true,
  },
  {
    id: "dhoop-astha-100g",
    category_id: "cat-dhoop",
    name: "Astha Dhoop Cone 100g / आस्था धूप कोन",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199353/venkateshwara/products/dhoop-astha.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199353/venkateshwara/products/dhoop-astha.webp"],
    is_image: true,
    mrp: 90,
    member_price: 75,
    wholesale_enabled: true,
    wholesale_price: 65,
    wholesale_min_qty: 12,
    is_available: true,
  },
  {
    id: "dhoop-vedshree-100g",
    category_id: "cat-dhoop",
    name: "Vedshree Dhoop Cone 100g / वेदश्री धूप कोन",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199353/venkateshwara/products/dhoop-vedshree.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199353/venkateshwara/products/dhoop-vedshree.webp"],
    is_image: true,
    mrp: 90,
    member_price: 75,
    wholesale_enabled: false,
    wholesale_price: null,
    wholesale_min_qty: null,
    is_available: true,
  },
  {
    id: "dhoop-vrinda-100g",
    category_id: "cat-dhoop",
    name: "Vrinda Dhoop Cone 100g / वृंदा धूप कोन",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199354/venkateshwara/products/dhoop-vrinda.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199354/venkateshwara/products/dhoop-vrinda.webp"],
    is_image: true,
    mrp: 90,
    member_price: 75,
    wholesale_enabled: false,
    wholesale_price: null,
    wholesale_min_qty: null,
    is_available: true,
  },

  // --- Kitchen Essentials ---
  {
    id: "turmeric-200g",
    category_id: "cat-kitchen",
    name: "Turmeric Powder 200g / हळद पावडर",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199358/venkateshwara/products/turmeric-200g.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199358/venkateshwara/products/turmeric-200g.webp"],
    is_image: true,
    mrp: 80,
    member_price: 70,
    wholesale_enabled: true,
    wholesale_price: 60,
    wholesale_min_qty: 20,
    is_available: true,
  },
  {
    id: "turmeric-500g",
    category_id: "cat-kitchen",
    name: "Turmeric Powder 500g / हळद पावडर",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199359/venkateshwara/products/turmeric-500g.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199359/venkateshwara/products/turmeric-500g.webp"],
    is_image: true,
    mrp: 180,
    member_price: 160,
    wholesale_enabled: true,
    wholesale_price: 140,
    wholesale_min_qty: 10,
    is_available: true,
  },
  {
    id: "gir-cow-ghee-250ml",
    category_id: "cat-kitchen",
    name: "Gir Cow Pure Ghee 250ml / गिर गायीचे शुद्ध तूप",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199355/venkateshwara/products/gir-cow-ghee-250ml.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199355/venkateshwara/products/gir-cow-ghee-250ml.webp"],
    is_image: true,
    mrp: 750,
    member_price: 690,
    wholesale_enabled: false,
    wholesale_price: null,
    wholesale_min_qty: null,
    is_available: true,
  },
  {
    id: "gir-cow-ghee-500ml",
    category_id: "cat-kitchen",
    name: "Gir Cow Pure Ghee 500ml / गिर गायीचे शुद्ध तूप",
    image_url: "https://res.cloudinary.com/d8mvq75f/image/upload/v1791199355/venkateshwara/products/gir-cow-ghee-250ml.webp",
    images: ["https://res.cloudinary.com/d8mvq75f/image/upload/v1791199355/venkateshwara/products/gir-cow-ghee-250ml.webp"],
    is_image: true,
    mrp: 1450,
    member_price: 1350,
    wholesale_enabled: true,
    wholesale_price: 1250,
    wholesale_min_qty: 6,
    is_available: true,
  },
];
